# in _config.yml
title: "Some MLOps Stuff"
author: Fernando Favoretti

execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/FernandoFavoretti/fernandofavoretti.github.io

exclude_patterns: [_build, .DS_Store, "**.ipynb_checkpoints"]

sphinx:
  config:
    language: en
