url: https://fernandofavoretti.github.io/

# Site settings
title: "Fernando Favoretti"
email: fernandofvprado@gmail.com
description: "Some MLOps stuff"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://linkedin.com/in/fernandofavoretti
  - title: github
    url: https://github.com/fernandofavoretti
  - title: instagram
    url: https://www.instagram.com/fefavoretti/


# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
